name: Pack Project
description: "Build and push nuget"

inputs:
  project:
    description: "Project name"
    required: true
  version:
    description: "Project Version"
    required: true
  nugetapikey:
    description: "nuget API key"
    required: true

runs:
  using: "composite"
  steps:
  - name: update version in csproj
    id: package_version
    uses: KageKirin/set-csproj-version@v0
    with:
      file: src/${{inputs.project}}/${{inputs.project}}.csproj
      version: ${{ inputs.version }}
      
  - name: Install dependencies
    shell: bash
    run: dotnet restore

  - name: dotnet build ${{inputs.project}}  
    shell: bash
    run: dotnet build src/${{inputs.project}} --configuration Release --no-restore

  - name: dotnet test ${{inputs.project}}
    shell: bash
    run: dotnet test src/${{inputs.project}}
    
  - name: dotnet pack ${{inputs.project}}
    shell: bash
    run: dotnet pack src/${{inputs.project}} -c Release --no-build
    
  - name: Publish Artifacts
    uses: actions/upload-artifact@v4
    with:
      name: ${{inputs.project}}-packages
      path: '**/${{inputs.project}}/bin/**/*.*nupkg'
    
  - name: Publish
    shell: bash
    run: dotnet nuget push **/${{inputs.project}}/bin/**/*.nupkg -k ${{ inputs.nugetapikey }} -s https://api.nuget.org/v3/index.json 
