name: Pack Digma.MassTransit.Integration

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  PROJECT: Digma.MassTransit.Integration
jobs:
  publish:
    name: publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: ./pack-action
        with:
          project: ${{ env.PROJECT }}
  