name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          7.0.x
          8.0.x
          9.0.x

    - name: Setup MSBuild (for .NET Framework)
      uses: microsoft/setup-msbuild@v1.1
          
    - name: Restore dependencies
      run: |
        dotnet restore
        nuget restore ./src/Tests/AutoInstrumentation.ConsoleAppNetFramework.csproj

    - name: Build
      run: dotnet build --no-restore

    - name: Test OpenTelemetry.Instrumentation.Digma.Tests
      run: |
        dotnet test ./src/OpenTelemetry.Instrumentation.Digma.Tests --no-build --verbosity normal
        
    - name: Test AutoInstrumentation.UnitTests
      run: |
        dotnet test ./src/Tests/AutoInstrumentation.UnitTests --framework net9.0 --no-build --verbosity normal
