name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
          9.0.x
          
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test OpenTelemetry.Instrumentation.Digma.Tests
      run: |
        dotnet test ./src/OpenTelemetry.Instrumentation.Digma.Tests --no-build --verbosity normal
        
    # - name: Test AutoInstrumentation.UnitTests
    #   run: |
    #     dotnet test ./src/Tests/AutoInstrumentation.UnitTests --framework net9.0 --no-build --verbosity normal

    - name: Test AutoInstrumentation.UnitTests
      run: |
        dotnet test ./src/Tests/AutoInstrumentation.UnitTests --framework net9.0 --no-build --logger "trx;LogFileName=test_results.trx"
        dotnet tool install -g trx2gh --add-source https://f2calv.pkgs.visualstudio.com/_packaging/trx2gh/nuget/v3/index.json
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
        trx2gh test_results.trx