name: Pack OpenTelemetry.Instrumentation.Digma

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  PROJECT: OpenTelemetry.Instrumentation.Digma
jobs:
  publish:
    name: publish nuget
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/pack
        with:
          project: ${{ env.PROJECT }}
  